# Generated by Django 3.2.23 on 2024-01-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_image_filter'),
        ('comments', '0002_rename_post_comment_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.posts'),
        ),
    ]
